name: github pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v6.0.0

      - uses: jontze/action-mdbook@v4.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          mdbook-version: 0.5.4
          use-toc: true
          toc-version: 0.15.4
          use-opengh: true
          opengh-version: 3.0.0
      - name: Show mdbook version
        run: mdbook --version
      - name: Show toc version
        run: mdbook-toc --version
      - name: Show open-on-gh version
        run: mdbook-open-on-gh --version

      - name: Build
        run: mdbook build

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v5.0.0
        with:
          path: ./book

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5.0.0
